zn "%SYS"
// Allow service calling for embedded python
do ##class(Security.Services).Get("%Service_CallIn",.prop)
set prop("Enabled")=1
set prop("AutheEnabled")=48
do ##class(Security.Services).Modify("%Service_CallIn",.prop)
Do ##class(Security.Users).UnExpireUserPasswords("*")
zpm "install iterm"
zn "USER"
zpm "install pretty-json"
; zpm "install webterminal"
zpm "load /opt/irisbuild/ -v":1
halt 

